"""Add Route models

Revision ID: add_route_models_manual
Revises: 50fd0a3fdf8c
Create Date: 2026-04-19 10:55:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = 'add_route_models_manual'
down_revision = '50fd0a3fdf8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create routes table
    op.create_table('routes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('crew_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_distance_meters', sa.BigInteger(), nullable=False, server_default=sa.text('0')),
    sa.Column('total_duration_seconds', sa.BigInteger(), nullable=False, server_default=sa.text('0')),
    sa.Column('polyline', Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=True), nullable=True),
    sa.Column('optimization_method', sa.String(length=50), nullable=False, server_default=sa.text("'ors'::character varying")),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['users.id'], name='fk_routes_crew_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Route model with spatial polyline for optimized waste collection routes'
    )
    op.create_index('ix_routes_crew_id', 'routes', ['crew_id'], unique=False)
    
    # Create route_stops table
    op.create_table('route_stops',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('route_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('incident_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_route_stops_incident_id_incidents', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name='fk_route_stops_route_id_routes', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Individual stops within a route'
    )
    op.create_index('ix_route_stops_route_id', 'route_stops', ['route_id'], unique=False)
    op.create_index('ix_route_stops_incident_id', 'route_stops', ['incident_id'], unique=False)
    
    # Add comments
    op.execute("COMMENT ON COLUMN routes.crew_id IS 'Assigned crew member ID'")
    op.execute("COMMENT ON COLUMN routes.status IS 'Route status: pending, active, completed, cancelled'")
    op.execute("COMMENT ON COLUMN routes.total_distance_meters IS 'Total route distance in meters'")
    op.execute("COMMENT ON COLUMN routes.total_duration_seconds IS 'Total route duration in seconds'")
    op.execute("COMMENT ON COLUMN routes.polyline IS 'Route polyline as PostGIS LINESTRING'")
    op.execute("COMMENT ON COLUMN routes.optimization_method IS 'Optimization method: ors, haversine_nn'")
    op.execute("COMMENT ON COLUMN routes.metadata_json IS 'Additional route metadata as JSON'")
    
    op.execute("COMMENT ON COLUMN route_stops.route_id IS 'Parent route ID'")
    op.execute("COMMENT ON COLUMN route_stops.incident_id IS 'Associated incident ID'")
    op.execute("COMMENT ON COLUMN route_stops.stop_order IS 'Order of this stop in the route'")
    op.execute("COMMENT ON COLUMN route_stops.status IS 'Stop status: pending, in_progress, completed, skipped'")
    op.execute("COMMENT ON COLUMN route_stops.estimated_arrival IS 'Estimated arrival time at this stop'")
    op.execute("COMMENT ON COLUMN route_stops.actual_arrival IS 'Actual arrival time at this stop'")
    op.execute("COMMENT ON COLUMN route_stops.notes IS 'Notes about this stop'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_route_stops_incident_id', table_name='route_stops')
    op.drop_index('ix_route_stops_route_id', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('ix_routes_crew_id', table_name='routes')
    op.drop_table('routes')
