"""Add Route and RouteStop models

Revision ID: 50fd0a3fdf8c
Revises: 001
Create Date: 2024-05-21 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50fd0a3fdf8c'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('crew_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Crew user assigned to execute this route'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='routestatus'), nullable=False, comment='Route lifecycle status'),
    sa.Column('total_distance_meters', sa.Integer(), nullable=True, comment='Total route distance in meters (ORS/fallback output)'),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True, comment='Total estimated travel duration in seconds (ORS/fallback output)'),
    sa.Column('polyline', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='PostGIS LINESTRING geometry of the route in WGS84 (lng/lat)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['users.id'], name=op.f('fk_routes_crew_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index('ix_routes_crew_id_status', 'routes', ['crew_id', 'status'], unique=False)
    op.create_index(op.f('ix_routes_created_at'), 'routes', ['created_at'], unique=False)
    op.create_index(op.f('ix_routes_crew_id'), 'routes', ['crew_id'], unique=False)
    op.create_index(op.f('ix_routes_status'), 'routes', ['status'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('route_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('incident_id', postgresql.UUID(as_uuid=True), nullable=False, comment='Incident serviced at this stop'),
    sa.Column('stop_order', sa.Integer(), nullable=False, comment='0-based or 1-based order; be consistent at service layer (recommended: 1-based for UI)'),
    sa.Column('status', sa.Enum('PENDING', 'SKIPPED', 'COMPLETED', name='routestopstatus'), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True, comment='ETA at this stop (optional; computed when route is generated/updated)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_route_stops_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_id', 'incident_id', name='uq_route_stops_route_incident'),
    sa.UniqueConstraint('route_id', 'stop_order', name='uq_route_stops_route_order')
    )
    op.create_index('ix_route_stops_route_id_order', 'route_stops', ['route_id', 'stop_order'], unique=False)
    op.create_index(op.f('ix_route_stops_incident_id'), 'route_stops', ['incident_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_stops_status'), 'route_stops', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_status'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_incident_id'), table_name='route_stops')
    op.drop_index('ix_route_stops_route_id_order', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_routes_status'), table_name='routes')
    op.drop_index(op.f('ix_routes_crew_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_created_at'), table_name='routes')
    op.drop_index('ix_routes_crew_id_status', table_name='routes')
    op.drop_table('routes')
    sa.Enum(name='routestopstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='routestatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
